# Generated by Django 4.0.4 on 2022-05-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_translate_text',
            field=models.TextField(default=' ', max_length=200000),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock')], default='Pop', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='text_cyrillic',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
